name: Build Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - docs
  push:
    branches:
      - docs

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Check Formatting
        run:  npm run check-formatting

      - name: Build Site
        run: npm run build
        env:
          HUGO_BASEURL: ${{ steps.pages.outputs.base_url }}

      - name: Deploy Site
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public